[project]
name = "pm25-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "joblib>=1.6.0",
    "langchain>=1.4.0",
    "langchain-anthropic>=1.7.1",
    "langchain-ollama>=1.1.0",
    "langgraph>=1.2.11",
    "matplotlib>=3.11.1",
    "numpy>=2.5.3",
    "pandas>=3.0.5",
    "python-dotenv>=1.2.3",
    "scikit-learn==1.8.0",
]
